# Generated by Django 5.0.6 on 2024-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('0', 'CERVEZA'), ('1', 'RON'), ('2', 'GIN'), ('3', 'VODKA'), ('4', 'TEQUILA'), ('5', 'BRANDY'), ('6', 'AGUARDIENTE'), ('7', 'WHISKY'), ('8', 'CHAMPAGNA'), ('9', 'VINO'), ('10', 'COCTEL')], max_length=2, verbose_name='Categoria')),
                ('name_bebida', models.CharField(max_length=60, verbose_name='Nombre bebida')),
                ('tamaño', models.CharField(choices=[('0', '375 ml'), ('1', '750 ml'), ('2', '1000 ml'), ('3', '210 ml'), ('4', '330 ml')], max_length=1, verbose_name='Tamaño')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
    ]
