# Generated by Django 5.0.6 on 2024-05-23 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sede', '0002_sede_direccion_sede_name_sede_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('last_name1', models.CharField(max_length=60, verbose_name='Primer Apellido')),
                ('last_name2', models.CharField(max_length=60, verbose_name='Segundo Apellido')),
                ('rol', models.CharField(choices=[('0', 'Administrador'), ('1', 'Mesero'), ('2', 'Cajero'), ('3', 'Bartender'), ('4', 'Seguridad')], max_length=1, verbose_name='Rol')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sede.sede')),
            ],
        ),
    ]
