# Generated by Django 5.0.6 on 2024-05-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('0', 'WINE AND BEER'), ('1', 'COCKTAILS')], max_length=2, verbose_name='Categoria')),
                ('name_bebida', models.CharField(max_length=60, verbose_name='Nombre bebida')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio')),
                ('detalle', models.CharField(max_length=100, verbose_name='Detalle')),
            ],
        ),
    ]
