# Generated by Django 5.0.6 on 2024-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nombre')),
                ('last_name1', models.CharField(max_length=60, verbose_name='Primer Apellido')),
                ('tipo_documento', models.CharField(choices=[('0', 'CC'), ('1', 'CE'), ('2', 'Pasaporte')], max_length=1, verbose_name='Tipo documento')),
                ('num_doc', models.IntegerField(verbose_name='Numero de documento')),
                ('telefono', models.IntegerField(null=True, verbose_name='Telefono')),
            ],
        ),
    ]
