# Generated by Django 5.0.6 on 2024-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sede', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='direccion',
            field=models.CharField(max_length=150, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='sede',
            name='name',
            field=models.CharField(max_length=60, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='sede',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='Telefono'),
        ),
    ]
